### PR TITLE
Master-prep-ekk into master

### PR DESCRIPTION
**Pull request by jajhall**
It had to happen sometime!

### CODE REVIEW

**Comment by jajhall** [comment]
@lgottwald and @jajhall have been effectively using this branch for weeks, so no review is required.

**Comment by jajhall** [comment]
@odow @mckib2 Don't try to switch to this immediately! 
This is phase 1 of merging in some other significant changes in the next week or so. Once this is done, there is a document that will guide users through the enhancements and changes. As discussed elsewhere, there are a few changes that will break some current uses of HiGHS.

**Comment by odow** [comment]
No problem. Please ping me when we should make a new release of the Julia binaries! Exciting stuff.

**Comment by mckib2** [comment]
Thanks @jajhall !  We had seen some strange errors in our MacOS build similar to https://github.com/ERGO-Code/HiGHS/issues/493#issuecomment-795135134 that we were not able to debug so we are still currently on an older version of HiGHS.  When this release happens it might be a good chance to resume testing and catch back up so we can finally provide a ranging interface

**Pull request merged**
