### PR TITLE
Fix master qp mods conflicts

### PR DESCRIPTION
**Pull request by jajhall**
This resolves the horrible merge conflicts in #629 and corrects one error in Highs.cpp that I spotted

### CODE REVIEW

**Comment by jajhall** [comment]
Little to review, but I've only run it through a few unit/instance tests, so please check that your non-trivial use of the QP solver is still OK through the changed code.

**Comment by feldmeier** [comment]
Thanks! I'll run some tests tomorrow

**Comment by feldmeier** [comment]
Thanks again. I had to resolve a couple more conflicts (e.g. when calling readMps). tests and instances run fine. I merged this into master-qp-mods, and will create a new merge request to get all the changes into master at once.

Interestingly, the behaviour (as in number of iterations) changed on some instances with this merge.

**Comment by jajhall** [comment]
Good. I guess that changes to the simplex solver mean that you're getting a different initial feasible solution sometimes. 
[Seasons Greetings 2021.pdf](https://github.com/ERGO-Code/HiGHS/files/7776291/Seasons.Greetings.2021.pdf)

**Pull request closed without merging**
