### PR TITLE
fix unintended behavior of RINS heuristic

### PR DESCRIPTION
**Pull request by lgottwald**
Just discovered this. The RINS heuristic implementation extends the original scheme by fixing additional variables, but the implemented behavior fixed additional variables before the RINS fixings where all applied.

### CODE REVIEW

**Comment by lgottwald** [comment]
Shortly testing the fix on a few instances, but heuristic success seems to be improved

**Comment by lgottwald** [comment]
The changes for the heuristic are ok, but there is one other (unrelated) bug that I need to investigate where the symmetry detection is not terminating

**Comment by lgottwald** [comment]
I would also want to merge this as it now fixes several bugs. One in the symmetry detection that already appeared several times before, but very rarely, and only on a long running instance which made it very hard to debug. I am glad I finally fixed it now. The bug in the primal heuristic seemed to decrease the success of the heuristic considerable and one other issue leading to bad restart decisions that appeared during my tests of the other changes.
Any objections @jajhall?

**Review by jajhall — APPROVED** [review]
Fine by me!

**Pull request merged**
