### PR TITLE
Reduce amount of similar code in HighsPathSeparator.cpp

### PR DESCRIPTION
**Pull request by fwesselm**
- While debugging I realized that HighsPathSeparator.cpp contains repetitive code. 
- I added two lambdas to simplify the code.
- Extensive testing showed that the code changes do not affect HiGHS behavior / performance (as expected).

### CODE REVIEW

**Review by jajhall — APPROVED** [review]
I know that duplicated code is to be avoided, but I don't see the point in eliminating it from code written a long time ago that is correct. I know that you're careful, and testing for changes in performance, but there's still the small chance of introducing errors. Ditto replacing conditional execution of the code in a loop with `continue`using the opposite logic. 

What are you trying to achieve?

**Comment by fwesselm** [comment]
> I know that duplicated code is to be avoided, but I don't see the point in eliminating it from code written a long time ago that is correct. I know that you're careful, and testing for changes in performance, but there's still the small chance of introducing errors. Ditto replacing conditional execution of the code in a loop with `continue`using the opposite logic.
> 
> What are you trying to achieve?

Three reasons for eliminating duplicate / similar code that come to my mind are increased maintainability, reduced error-proneness, and potentially increased code coverage. The changes in this PR were qualified on 850+ instances.

**Comment by jajhall** [comment]
There are excellent reasons for avoiding duplicate code when first writing it but, once it's running I have to question the value of "fiddling" with it. Fixing bugs is far a more valuable use of time and benchmarking resources.

On reflection, perhaps there's a very small chance that if you eliminate duplicated code and behaviour changes, then it indicates that there was an error due to having a difference between two code sections that should have been identical. Still seems like a long shot to me.

**Comment by lkapelevich** [comment]
> Three reasons for eliminating duplicate / similar code that come to my mind are increased maintainability, reduced error-proneness, and potentially increased code coverage. The changes in this PR were qualified on 850+ instances.

Simplifying older code will also help future readers.

**Pull request merged**
