### PR TITLE
Pyomo highs

### PR DESCRIPTION
**Pull request by WTFHCN**
Hello, I helped you write a Solver that connects Pyomo to HIGHS. For specific use, please refer to the test I wrote.

But some problems
+ MIP problem is not added
+ MPS file cannot be used, please refer to my last question https://github.com/ERGO-Code/HiGHS/issues/571
+ The branch inherited my previous changes to the answer file https://github.com/ERGO-Code/HiGHS/pull/569

I hope you can make some suggestions.

### CODE REVIEW

**Comment by odow** [comment]
@WTFHCN this might be more suited to a contribution in the Pyomo repository: https://github.com/Pyomo/pyomo/tree/main/pyomo/solvers/plugins/solvers

This is what its being done with the PuLP interface: https://github.com/coin-or/pulp/pull/477
And the JuMP interface is in a separate repo https://github.com/jump-dev/HiGHS.jl

**Comment by mckib2** [comment]
I will echo @odow here -- a better design choice is to have this interface live somewhere else where you can control it.  Multiple packages are using HiGHS as a backend including several Python modules.  This would also place a burden on HiGHS maintainers/developers to maintain an interface they didn't write and don't have a stake in

**Comment by jajhall** [comment]
Thanks for your comments @odow and @mckib2 . PR #569 has been merged since it fixes an error (missing spaces)  in the code that prints a solution file, and I've just fixed issue #571 - which only related to recognition of very short names in free format MPS, not free format itself. 

So, @WTFHCN , please follow the suggestions of @odow and @mckib2 and add your interface as a contribution to the Pyomo repository. That would also seem to be a better way of publicising to Pyomo users that there is an interface to HiGHS. 

Hence I'll not approve this PR to be merged into master.

When you say that there is a "problem" that the MIP problem is not added, is that just because there's no interface, or some problem with HiGHS? The HiGHS MIP solver is exceptionally powerful now - it's overtaken SCIP on one of the two MIPLIB 2017 measures (problems solved in 3600s) - and will be of great value to open source users of modelling languages and interfaces like Pyomo. So, let's keep talking!

Finally, many thanks for the work you're doing and for keeping us on our toes!

**Comment by WTFHCN** [comment]
OK! I will continue to try to optimize the code structure and add MIP questions!

**Comment by odow** [comment]
> it's overtaken SCIP on one of the two MIPLIB 2017 

Are these benchmarks public?

**Comment by jajhall** [comment]
Not yet. We want to improve solution speed a bit more first so that we beat SCIP on that, too.

**Comment by jajhall** [comment]
Thanks for the heads-up on ECOLE. I've seen a few packages using SCIP - some probably illegally. If nothing else, SCIP is the only MIP solver in Google's OR-Tools. They have a disclaimer, but I know that OR-Tools is being used commercially for MIP work. Google will be offering HiGHS as a solver in due course.

The HiGHS benchmark results are public. It's only a the limited documentation that's preventing us from promoting the solvers more.

**Pull request closed without merging**
