### PR TITLE
Fix 1908

### PR DESCRIPTION
**Pull request by jajhall**
Run clang formatting

### CODE REVIEW

**Comment by jajhall** [comment]
@fwesselm There were some changes when I ran clang formatting locally. However, there does seem to be an error in the clang format test on GitHub.

@galabovaa Please would you look into this

**Comment by fwesselm** [comment]
@jajhall I also saw that there were changes when I ran the clang formatting. The test-clang-format now seems to run fine again in my branch. If you like, I could create another pull request.

**Comment by jajhall** [comment]
So, I've run `clang-format` on my desktop running Ubuntu 22.04 (and `clang-format` `14.0.0-1ubuntu1.1`), and the `test-clang-format` CI tests work OK

I've got stuff to push from my laptop running Ubuntu 24.04 (and `clang-format` `18.1.3 (1ubuntu1)`) and will see whether the `test-clang-format` CI tests work OK

**Comment by jajhall** [comment]
Fine now!

**Pull request merged**
