### PR TITLE
C API: add Highs_getInt64InfoValue

### LINKED ISSUE #747: C API: missing Highs_getLongInfoValue
The C API is missing a function to query `record_int64` info values:

https://github.com/ERGO-Code/HiGHS/blob/17237a320d5c32a95c18e1e8cf2ef4a365e9e889/src/lp_data/HighsInfo.h#L251-L254

x-ref: https://github.com/jump-dev/HiGHS.jl/issues/86

### PR DESCRIPTION
**Pull request by odow**
Closes #747

Not sure if this is the best name. Open to other suggestions.

### CODE REVIEW

**Comment by jajhall** [comment]
The name is fine, but we have a problem in the C++ API since `mip_node_count` is always `int64_t`

**Comment by odow** [comment]
Hmm yeah. Admittedly, I didn't try to compile this locally, because I assumed the fix was straight forward.

**Comment by jajhall** [comment]
No problem. You've exposed a latent issue in the C++ API, so thanks!

**Comment by jajhall** [comment]
Thanks @lgottwald

**Pull request merged**
