### PR TITLE
[docs] re-organize the structure of the documentation, misc. editing

### PR DESCRIPTION
**Pull request by odow**
Preview link once CI finishes: https://ergo-code.github.io/HiGHS/previews/PR1224

The diff is a bit horrible. I didn't write entirely new sections, it's just moving a few bits around. There's still a lot that can be improved, but we're heading in the right direction.

### CODE REVIEW

**Comment by odow** [comment]
The main changes:

 * An installation page
 * An "Interfaces" group
 * Math and heading fixes

## New

image

## Old

image

**Comment by jajhall** [comment]
Thanks for this. There are some nice improvements. However, the `Guide` section is hidden too deeply: indeed, for a moment I thought you'd deleted it!

The `Guide` section acts as an overview of what HiGHS can do, and not just for the Python interface. Although the links are to the Python examples, the method names are the same as in C++, and (generally) differ from the C and FORTRAN APIs in just a constant prefix. 

I'll add text to the `About` and start of the `Guide, and move it back to the top level.

**Comment by jajhall** [comment]
Where do you see the room for improvement?

**Comment by jajhall** [comment]
> Where do you see the room for improvement?

Not saying that there isn't!

**Comment by odow** [comment]
> The Guide section acts as an overview of what HiGHS can do, and not just for the Python interface. Although the links are to the Python examples, the method names are the same as in C++, and (generally) differ from the C and FORTRAN APIs in just a constant prefix.

Ah. I got confused because it linked to the Python

**Comment by odow** [comment]
> Where do you see the room for improvement?

Let me open an issue

**Comment by odow** [comment]
https://github.com/ERGO-Code/HiGHS/issues/1225

**Pull request merged**
