### PR TITLE
Extend highs_sharp_api: Add passMip, getInfo, setSolution

### PR DESCRIPTION
**Pull request by jannicklange**
refs #972

### CODE REVIEW

**Comment by jajhall** [comment]
Thanks. It looks as if you've made modifications to the C# API that I presume are correct, but conflict with `https://github.com/ERGO-Code/HiGHS/blob/master/examples/call_highs_from_csharp.cs`, resulting in some CI failures. If you've got time, could you look at the CI failures, work out how to modify `call_highs_from_csharp.cs` and add it to the PR?

**Comment by jannicklange** [comment]
I added an argument to the HighsModel ctor. The example is now adjusted accordingly.

I am uncertain regarding the `private const string highslibname = "libhighs";`, though. In your initial C# API, it was set to `highs`.
When I compile the code under linux, `HiGHS\build\lib` contains `.so` files that are called `libhighs.so(.1.2.2)` The dll in your release package also is called `libhighs.dll`. However, when I compile under Windows, the binaries are called `HiGHS\build\bin\Debug\highs.(dll / exe)`.

We need to settle on one name. I'd suggest to go with libhighs, since this already is used by the official package, and the "linux world". Do you know, where the dll names are specified (and why the Win-Debug build produces a DLL with a different name than used in the release package)?

**Comment by jajhall** [comment]
> I added an argument to the HighsModel ctor. The example is now adjusted accordingly.

Thanks: the CI tests pass

> I am uncertain regarding the `private const string highslibname = "libhighs";`, though. In your initial C# API, it was set to `highs`. When I compile the code under linux, `HiGHS\build\lib` contains `.so` files that are called `libhighs.so(.1.2.2)` The dll in your release package also is called `libhighs.dll`. However, when I compile under Windows, the binaries are called `HiGHS\build\bin\Debug\highs.(dll / exe)`.
> 
> We need to settle on one name. I'd suggest to go with libhighs, since this already is used by the official package, and the "linux world". Do you know, where the dll names are specified (and why the Win-Debug build produces a DLL with a different name than used in the release package)?

Thanks for raising this. I'll leave @galabovaa to look at it

**Review by jajhall — APPROVED** [review]
Great, thanks!

**Pull request merged**
