### PR TITLE
avoid using primal_feasibility_tolerance for MIP presolve, use mip_fe…

### PR DESCRIPTION
**Pull request by lgottwald**
…asibility_tolerance instead.

Realized this undesired behavior due to #765. For MIP behavior it should be sufficient to alter the mip_feasibility_tolerance option.

### CODE REVIEW

**Review by jajhall — APPROVED** [review]
Fine by me, and consistent with the setting of `options.primal_feasibility_tolerance` in `HighsLpRelaxation.cpp`. 

I find `feastol` rather opaque, since `options.dual_feasibility_tolerance` is also used in presolve, so I suggest that `primal_feasibility_tol(erance)` is used. Indeed, since the word "primal" is only associated with feasibility (and the setting `kPrimalInfeasible`) in `HPresolve.cpp`, if you want something short, use `primal_tol`. For consistency, I suggest that you also introduce `dual_tol` for `options.dual_feasibility_tolerance`.

I also see some "magic numbers" in calculations like
`impliedBound > implRowDualLower[row] + 1000 * feastol` and ``
For security and readability, it would be better if these were defined constants

**Comment by lgottwald** [comment]
The numbers are a bit magic, but also not entirely, as they are a relative threshold over the feasibility tolerance. It is not only used in HPresolve this way so I would replace this separately.

I renamed to primal_feastol now, to be also consistent with the naming of the field in the MIP solver class (feastol).

I did not introduce a similar field for the dual feasibility tolerance because I am not entirely sure about the proper intended behavior. The dual feasibility tolerance would be used for some dual reductions during presolve and it might be valuable, even for MIP to allow to adjust it differently via options.

For the primal_feasibility_tolerance, however, it overlaps with the mip_feasibility_tolerance, and for MIP clearly the latter should be used also presolve.

Do you think the mip_feasibility_tolerance should also be used for dual reductions when presolving a MIP?

**Comment by jajhall** [comment]
Sorry, by `magic`, I don't mean that they aren't well considered, rather that they are hard-coded as specific values in multiple places. If you ever wanted to change this value, all occurrences of 1000 would have to be edited, and not all 1000's might relate to the same usage

> Do you think the mip_feasibility_tolerance should also be used for dual reductions when presolving a MIP?

No, I was just thinking that since you are setting `primal_feastol ` to `options.mip_feasibility_tolerance` or `options.primal_feasibility_tolerance` according to whether the problem being presolved is a MIP or LP, for clarity it would make sense to set a local value of `dual_feastol` to `options.dual_feasibility_tolerance`. However, it may well be that the dual tolerance is used in very different places, so there's no comparison to be made.

**Comment by lgottwald** [comment]
Currently there is no analogy because MIP does not have a counterpart for the dual feasibility tolerance, hence there is no overlap of use that needs to be streamlined by a common variable dual_feastol. The intent of the field primal_feastol is to allow usage of the same primal tolerance for MIP and LP presolve and streamline the difference in how they are represented in the options. So for the dual feasibility we could do either of the following:

1. Define dual_feasibility_tolerance to affect LP and reductions based on LP-duality in LP and MIP presolve
2. Define dual_feasibility_tolerance to only affect LP and hard-code a dual_feasibility_tolerance value as relative factor to the MIP feasibility tolerance so that setting the option dual_feasibility_tolerance does not affect MIP presolve and mip_feasibility_tolerance is the only option affecting MIP.

I would currently favor option 1 because it seems more logical to me. It allows more control and also avoids arbitrarily using a dual_feasibility_tolerance value that is derived from the mip_feasibility_tolerance, as I feel there is no good argument of why that might be a good idea. There is only limited duality in MIP and implied bounds on the dual multipliers in MIP can only be derived from non-boxed continuous columns.

**Comment by jajhall** [comment]
Thanks, let's go with option 1

**Pull request merged**
