### PR TITLE
Fix bugs

### LINKED ISSUE #907: Presolve causes infeasible MIP
Might be the same as #902.

MPS file: [bug.mps.txt](https://github.com/ERGO-Code/HiGHS/files/9043043/bug.mps.txt)

Formulation is quite verbose, because it's a MILP transformed automatically from a Sudoku problem using AllDifferent constraints.

```Julia
julia> HiGHS_jll.highs() do exe
           run(`$exe bug.mps`)
       end
Running HiGHS 1.2.1 [date: , git hash: ]
Copyright (c) 2022 ERGO-Code under MIT licence terms
Number of BV entries in BOUNDS section is 1710
Number of LI entries in BOUNDS section is 51
Number of UI entries in BOUNDS section is 51
MIP  bug has 999 rows; 1818 cols; 6867 nonzeros; 1791 integer variables
Presolving model
702 rows, 1428 cols, 5195 nonzeros
459 rows, 1428 cols, 3665 nonzeros
Objective function is integral with scale 1

Solving MIP model with:
   459 rows
   1428 cols (1377 binary, 51 integer, 0 implied int., 0 continuous)
   3665 nonzeros

( 0.0s) Starting symmetry detection
( 0.0s) No symmetry present

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   0               inf                  inf        0      0      0         0     0.0s
         0       0         0   0.00%   0               inf                  inf        0      0      6       794     0.0s

59.5% inactive integer columns, restarting

Solving report
  Status            Optimal
  Primal bound      inf
  Dual bound        inf
  Gap               inf
  Solution status   -
  Timing            0.60 (total)
                    0.02 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     6169 (total)
                    0 (strong br.)
                    922 (separation)
                    4014 (heuristics)
ERROR:   MIP solver claims optimality, but with num/sum/max primal(-1/inf/inf) infeasibilities
Process(`/Users/oscar/.julia/artifacts/b22cc32ff7b7fd1398043f1f6276b38d00b63864/bin/highs bug.mps`, ProcessExited(0))
```

Turning off presolve works, but it's quite slow:
```Julia
julia> HiGHS_jll.highs() do exe
           run(`$exe --presolve=off bug.mps`)
       end
Running HiGHS 1.2.1 [date: , git hash: ]
Copyright (c) 2022 ERGO-Code under MIT licence terms
Number of BV entries in BOUNDS section is 1710
Number of LI entries in BOUNDS section is 51
Number of UI entries in BOUNDS section is 51
MIP  bug has 999 rows; 1818 cols; 6867 nonzeros; 1791 integer variables

Presolve is switched off
Objective function is integral with scale 1

Solving MIP model with:
   999 rows
   1818 cols (1710 binary, 81 integer, 0 implied int., 27 continuous)
   6867 nonzeros

( 0.0s) Starting symmetry detection
( 0.0s) No symmetry present

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   0               inf                  inf        0      0      0         0     0.0s
         0       0         0   0.00%   0               inf                  inf        0      0      6       738     0.0s

Solving report
  Status            Optimal
  Primal bound      0
  Dual bound        0
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    0 (objective)
                    0 (bound viol.)
                    1.35891298214e-13 (int. viol.)
                    0 (row viol.)
  Timing            3.54 (total)
                    0.00 (presolve)
                    0.00 (postsolve)
  Nodes             92
  LP iterations     23509 (total)
                    0 (strong br.)
                    3257 (separation)
                    10120 (heuristics)
Process(`/Users/oscar/.julia/artifacts/b22cc32ff7b7fd1398043f1f6276b38d00b63864/bin/highs --presolve=off bug.mps`, ProcessExited(0))
```

For perspective, Gurobi gives:

```julia
shell> gurobi_cl bug.mps
Set parameter LogFile to value "gurobi.log"
Using license file /Users/oscar/gurobi.lic

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (mac64[x86])
Copyright (c) 2022, Gurobi Optimization, LLC

Read MPS format model from file bug.mps
Reading time = 0.00 seconds
: 999 rows, 1818 columns, 6867 nonzeros
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 999 rows, 1818 columns and 6867 nonzeros
Model fingerprint: 0xc33aa9d1
Variable types: 27 continuous, 1791 integer (1710 binary)
Coefficient statistics:
  Matrix range     [1e+00, 9e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [1e+00, 9e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 540 rows and 434 columns
Presolve time: 0.01s
Presolved: 459 rows, 1384 columns, 3621 nonzeros
Variable types: 0 continuous, 1384 integer (1333 binary)

Root relaxation: objective 0.000000e+00, 764 iterations, 0.02 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    0.00000    0  198          -    0.00000      -     -    0s
     0     0    0.00000    0  286          -    0.00000      -     -    0s
     0     0    0.00000    0  260          -    0.00000      -     -    0s
*    0     0               0       0.0000000    0.00000  0.00%     -    0s

Cutting planes:
  Gomory: 42
  Cover: 85
  Implied bound: 2
  Clique: 261
  MIR: 68
  StrongCG: 23
  GUB cover: 68
  Zero half: 71
  RLT: 3
  Relax-and-lift: 60

Explored 1 nodes (7395 simplex iterations) in 0.61 seconds (0.40 work units)
Thread count was 8 (of 8 available processors)

Solution count 1: 0 

Optimal solution found (tolerance 1.00e-04)
Best objective 0.000000000000e+00, best bound 0.000000000000e+00, gap 0.0000%
```

### PR DESCRIPTION
**Pull request by lgottwald**
fixes #907 and another bug

### CODE REVIEW

**Comment by jajhall** [comment]
@galabovaa has a branch 

https://github.com/ERGO-Code/HiGHS/compare/python-string-options-breaking-master

with minimal CI tests dropped so that all pass. Could you merge this branch into fix-bug (or create a branch of fix-bug with this merge) so that we can see whether any further CI tests have failed.

I'll coordinate with @galabovaa to see who will fix the original CI failures. They seem to be due to @svigerske modifying things!

**Comment by svigerske** [comment]
> I'll coordinate with @galabovaa to see who will fix the original CI failures. They seem to be due to @svigerske modifying things!

There were no CI failures in #905. `on` and `off` are now recognized as possible values for boolean options as well.
It didn't intend to break string option `presolve`, which can be `on`, `off`, and `change`.
If you derive the option datatype from the option value at some place, then this may be a bit fragile.

**Comment by jajhall** [comment]
To be precise, I understand from @galabovaa that in #905, some of the CI tests didn't run - either due to changes in GitHub, or due to work she was doing on building the Python interface to HiGHS - and this masked the failures we're seeing now.

**Comment by lgottwald** [comment]
I merged the branch and fixed the formatting. Hopefully tests pass now

**Review by jajhall — APPROVED** [review]
Fine by me

**Pull request merged**
