### PR TITLE
Fix minor sanitizer issues and add optional Meson workflow to run the sanitizers

### PR DESCRIPTION
**Pull request by Coloquinte**
Related to #1576 

Some very minor sanitizer issues remain, as can be seen in the logs that are uploaded [by the Github action here](https://github.com/Coloquinte/Highs-solver/actions/runs/7513161918)
* A small memory leak (could not reproduce locally)
* A typing issue when casting an option
* Null pointer arithmetic when manipulating an empty slice
* A data race between `HighsSplitDeque::WorkerBunk::waitForNewTask` and `HighsSplitDeque::injectTaskAndNotify(HighsTask*)` (could not reproduce on github)

### CODE REVIEW

**Comment by galabovaa** [comment]
Thank you, these look great so far!

**Comment by jajhall** [comment]
Thanks: I can see why the source code modifications sanitize what was originally written

**Comment by Coloquinte** [comment]
Thanks! There is one minor leak left, but I'm not sure that's really a bug

**Comment by jajhall** [comment]
Thanks for all these! Have a good weekend

**Comment by Coloquinte** [comment]
Thank you! You too :)

**Pull request merged**
