### PR TITLE
Issue 1472 - Add a branch-and-price example for the python interface

### PR DESCRIPTION
**Pull request by guifcoelho**
- Fixed a bug where the master problem was being reset without respecting the new bounds of the columns in the node. 
- Added 2 asserts to make sure no index is repeated when solving the nodes in the branch-and-price part and to make sure no column assigned to 1 in the node is returned back with a fractional value.
- Changed `N` to 60 and `capacity` to 15 as suggested

### CODE REVIEW

**Comment by jajhall** [comment]
Works perfectly for N=15 and N=25. Now running for N=50, but I don't expect any problems

**Comment by jajhall** [comment]
It's solved the N=100; capacity =50 problem OK now

**Comment by guifcoelho** [comment]
That's great! I'll let you know if I come up with any other interesting python examples to add.

**Comment by jajhall** [comment]
Thanks. I've no idea about the efficiency of your solver, and it makes me wonder about the scope for implementing branch-and-price within the HiGHS MIP solver, in order to leverage its power.

That said, I'd like to publicise your contribution via a HiGHS post on LinkedIn. Do you have a LinkedIn account that I can connect to and refer to in my post.

I'll also add some comments to your code and remove the couple of unnecessary things

**Comment by jajhall** [comment]
Thanks. I've no idea about the efficiency of your solver, and it makes me wonder about the scope for implementing branch-and-price within the HiGHS MIP solver, in order to leverage its power.

That said, I'd like to publicise your contribution via a HiGHS post on LinkedIn. Do you have a LinkedIn account that I can connect to and refer to in my post.

I'll also add some comments to your code and remove the couple of unnecessary things that I mentioned

**Comment by guifcoelho** [comment]
I believe the column generation part is pretty standard, so unless you know anything on the solver's internals that could help I wouldn't waste time on it. But I'm 100% sure the branching part could be improved a lot, specially if done within Highs' code.

We are already connected on LinkedIn. You can find me [here](https://www.linkedin.com/in/coelhogf) .

**Comment by jajhall** [comment]
I can believe that what you've done is fairly standard. 

For me the value is in providing an extensive Python example. I guess that there's little to learn from it coding-wise for for good Python programmers, but seeing examples of how to do a range of things in algorithmic programming may be very valuable for programmers (such as me!) in other languages looking to write sophisticated Python without learning the language from scratch.

My only thought in the column generation is to use the barrier solver for the master problems. My colleague Jacek Gondzio is always saying how it's valuable for stabilising dual values. 

In due course I'll probably get a Master's student to study column generation and  and produce a variant of your code to solve models like cutting stock.

Writing an internal column generation code in HiGHS is a possible PhD activity

**Comment by jajhall** [comment]
> We are already connected on LinkedIn. You can find me here .

Sorry, and thanks. I did a very poor search for you on LinkedIn last night

**Comment by guifcoelho** [comment]
Now I see what you mean. That's a very interesting research topic. In any case, let me know if I can help.

**Comment by jajhall** [comment]
I've run your example past @mathgeekcoder, and he's made quite a lot of changes. See #1488

The original aim was to improve documentation, and indicate where you cut corners algorithmically to keep the implementation short and simple, and indicate where your overall algorithm is dependent on being applied to the bin packing problem.

Hopefully they don't obscure the simplicity of your original version. It would be great if you have time to look at the modified code and make comments. Once you're happy, I'll publicise it to users.

I don't see how to add you as a reviewer of #1488 so let me know if you can't comment

**Comment by guifcoelho** [comment]
Hi Julian, I've made a comment on the PR.

**Pull request merged**
