### PR TITLE
fix missing virtual dtor

### PR DESCRIPTION
**Pull request by lgottwald**
I get a warning since delete is called on a sublass of type `Pricing` via a pointer of type `Pricing`, but the class does not have a virtual destrucutor. So I think the warning of the compiler is justified and this is a bug which is fixed here.

```
usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:81:2: warning: delete called on 'Pricing' that is abstract but has non-virtual destructor [-Wdelete-abstract-non-virtual-dtor]
        delete __ptr;
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:292:4: note: in instantiation of member function 'std::default_delete<Pricing>::operator()' requested here
          get_deleter()(std::move(__ptr));
          ^
/home/leona/projects/highs/src/qpsolver/solver.cpp:138:7: note: in instantiation of member function 'std::unique_ptr<Pricing, std::default_delete<Pricing> >::~unique_ptr' requested here
      std::unique_ptr<Pricing>(new DevexPricing(runtime, basis, redcosts));
```

### CODE REVIEW

**Comment by lgottwald** [comment]
Some less critical warnings in the qpsolver are here:
```
In file included from /home/leona/projects/highs/src/qpsolver/matrix.hpp:7:
/home/leona/projects/highs/src/qpsolver/parallel.hpp:62:13: warning: unused function 'parallel_for_obo' [-Wunused-function]
static void parallel_for_obo(HighsInt nb_elements,
            ^
In file included from /home/leona/projects/highs/src/qpsolver/solver.cpp:1:
In file included from /home/leona/projects/highs/src/qpsolver/solver.hpp:7:
/home/leona/projects/highs/src/qpsolver/nullspace.hpp:25:12: warning: private field 'runtime' is not used [-Wunused-private-field]
  Runtime& runtime;
           ^
In file included from /home/leona/projects/highs/src/qpsolver/solver.cpp:13:
In file included from /home/leona/projects/highs/src/qpsolver/dantzigpricing.hpp:5:
/home/leona/projects/highs/src/qpsolver/reducedcosts.hpp:10:12: warning: private field 'runtime' is not used [-Wunused-private-field]
  Runtime& runtime;
```
If you want to fix them too @feldmeier , feel free to add to this branch

**Comment by galabovaa** [comment]
Thank you for fixing one / flagging up the rest of the issues, I was having trouble with this one too

**Review by jajhall — COMMENTED** [review]
Modification is fine, but CI tests appear not to be passing

**Comment by lgottwald** [comment]
CI tests should be unaffected, except clang-format, but for that I checked. There seem to be, however, some problems today regarding github runners. I restarted the CI runs now.

**Comment by lgottwald** [comment]
I just merged master again and now CI seems to pass even though the difference was only the `CODE_OF_CONDUCT.md` :woman_shrugging:

**Review by jajhall — APPROVED** [review]
CI passed, so merge

**Pull request merged**
