### PR TITLE
BLD: `meson` updates for SciPy

### PR DESCRIPTION
**Pull request by HaoZeke**
Also includes a fix for #1294.

Addresses the [latest review](https://github.com/scipy/scipy/pull/19255#issuecomment-1925424141) for SciPy integration.

### CODE REVIEW

**Comment by HaoZeke** [comment]
@galabovaa and @jajhall this should be ready to go.

**Review by galabovaa — APPROVED** [review]
looks good to me!

**Comment by barracuda156** [comment]
@HaoZeke Why does it refer only to LLVM? GCC needs that check and `-latomic` flag.

**Comment by HaoZeke** [comment]
> @HaoZeke Why does it refer only to LLVM? GCC needs that check and `-latomic` flag.

I believe that is covered by this section:

```cmake
if(MSVC)
  set(HAVE_CXX_ATOMICS_WITHOUT_LIB True)
elseif(LLVM_COMPILER_IS_GCC_COMPATIBLE OR CMAKE_CXX_COMPILER_ID MATCHES "XL")
  # First check if atomics work without the library.
  check_working_cxx_atomics(HAVE_CXX_ATOMICS_WITHOUT_LIB)
  # If not, check if the library exists, and atomics work with it.
  if(NOT HAVE_CXX_ATOMICS_WITHOUT_LIB)
    check_library_exists(atomic __atomic_fetch_add_4 "" HAVE_LIBATOMIC)
    if(HAVE_LIBATOMIC)
      list(APPEND CMAKE_REQUIRED_LIBRARIES "atomic")
      check_working_cxx_atomics(HAVE_CXX_ATOMICS_WITH_LIB)
      if (NOT HAVE_CXX_ATOMICS_WITH_LIB)
        message(FATAL_ERROR "Host compiler must support std::atomic!")
      endif()
    else()
      message(FATAL_ERROR "Host compiler appears to require libatomic, but cannot find it.")
    endif()
  endif()
endif()
```

Would be best if you could try it though, I don't have a 32-bit machine to check against.

**Comment by barracuda156** [comment]
@HaoZeke If, counter-intuitively, `LLVM_COMPILER_IS_GCC_COMPATIBLE` evaluates as true for GCC, it probably will work.

**Comment by HaoZeke** [comment]
> @HaoZeke If, counter-intuitively, `LLVM_COMPILER_IS_GCC_COMPATIBLE` evaluates as true for GCC, it probably will work.

Ah, my bad, that's unlikely, I opened #1604 with a modified fix.

**Pull request merged**
