### PR TITLE
First batch of changes for restructuring of QP solver

### PR DESCRIPTION
**Pull request by feldmeier**

### CODE REVIEW

**Comment by jajhall** [comment]
There's a strange error with the Meson build test. I'll investigate

**Comment by galabovaa** [comment]
Hi Julian, 

Thank you! I struggled to get this far. I will look again and email you when I have an idea. 

Shall we chat some time tomorrow? 

Ivet

**Comment by HaoZeke** [comment]
> @HaoZeke @galabovaa The meson build appears to fail because @feldmeier has created new files `qpsolver/a_quass.cpp` and `qpsolver/a_asm.cpp`, and neither `qpsolver_a_quass.cpp.o` nor `qpsolver_a_asm.cpp.o` appears in the linking line of the meson build test output. This leads to
> 
> > /home/runner/work/HiGHS/HiGHS/bbdir_test/../src/lp_data/Highs.cpp:3177: undefined reference to `solveqp(Instance&, Settings&, Statistics&, QpModelStatus&, QpSolution&, HighsTimer&)'
> 
> which is defined in `qpsolver/a_quass.cpp`
> 
> * How is the list of object files in the meson build defined?
> * How to we accommodate the creation of new source code files?

Hi @jajhall,

The files need to be added to `$GITROOT/src/meson.build` around here:

```meson
_srcs = [
...,
    'qpsolver/basis.cpp',
    'qpsolver/quass.cpp',
    'qpsolver/ratiotest.cpp',
    'qpsolver/scaling.cpp',
    'qpsolver/perturbation.cpp',
    'qpsolver/a_quass.cpp',
    'qpsolver/a_asm.cpp',
...,
]
```

Also, unrelated, but would it be useful to have developer access to the repo, then I could push these kind of build system fixes to the PRs directly.

**Comment by jajhall** [comment]
Thanks @HaoZeke I've made the modification to `src/meson.build`

**Pull request merged**
