### PR TITLE
Fix incorrect bound checks

### PR DESCRIPTION
**Pull request by fwesselm**
Fix incorrect signs when comparing with `kHighsInf`.

### CODE REVIEW

**Review by jajhall — APPROVED** [review]
Interesting. I guess the first case doesn't matter, as rounding -inf gives -inf.

If the second was used in error, I guess it might have shown up spectacularly, but I'd have to follow through the subsequent actions properly

**Comment by fwesselm** [comment]
> Interesting. I guess the first case doesn't matter, as rounding -inf gives -inf.
> 
> If the second was used in error, I guess it might have shown up spectacularly, but I'd have to follow through the subsequent actions properly

I can also run the entire test suite for this change, if you like. Just to see if any problem is affected...

**Comment by fwesselm** [comment]
> > Interesting. I guess the first case doesn't matter, as rounding -inf gives -inf.
> > If the second was used in error, I guess it might have shown up spectacularly, but I'd have to follow through the subsequent actions properly
> 
> I can also run the entire test suite for this change, if you like. Just to see if any problem is affected...

I started testing and will report back tomorrow.

**Comment by jajhall** [comment]
Failure is due to odd behaviour for new CI test

**Pull request merged**
