### PR TITLE
X qp solver

### PR DESCRIPTION
**Pull request by galabovaa**
Merge of QP solver and minor crossover update, this branch (the latest commit) builds the Julia library with no issues! :)

### CODE REVIEW

**Review by jajhall — APPROVED** [review]
Lots of changes. I'm happy with mine, as they don't affect the core functionality.

Michael's QP solver looks good to go

**Comment by galabovaa** [comment]
image

**Comment by jajhall** [comment]
> Trying to link with HiGHS I get the following errors @feldmeier
> 
> image

How were you trying to link?

I've managed to link OK with my local use of the example files call_highs_from_cpp.cpp (once I'd fixed a bug in it) and call_highs_from_c.c

**Comment by feldmeier** [comment]
Were you trying to link a custom executable with the HiGHS library? or did this happend during a normal build of the HiGHS executable?

**Pull request merged**
