### PR TITLE
highspy: updated highs_linear_expression to be immutable for issue #1888

### LINKED ISSUE #1888: highspy: highs_linear_expression.__add__ modifies self
The following code shows that adding to a linear_expression modifies it. This is highly problematic, if the linear expression is reused several times in the code.

```import highspy
h = highspy.Highs()
x = h.addVariable()
linear_expression = 1*x
assert linear_expression.constant == 0
other_linear_expression = linear_expression + 1
assert linear_expression.constant == 0, "Ooops linear_expression has been modified"
```

### PR DESCRIPTION
**Pull request by mathgeekcoder**
Changes should fix #1888

* changed highs_linear_expression to be immutable by default
* added `__repr__` for easier debugging and pretty print linear expressions
* added `__iadd__` for mutable operations
* added `qsum` for faster aggregation
* added `expr == [lb,ub]` -> `lb <= expr <= ub` syntax 
* updated chained comparison support to work in immutable setting

Note there are some low-risk caveats for the chained comparison support.  I have documented them in the code.  Though I believe the benefits outweigh the potential concerns.

### CODE REVIEW

**Comment by odow** [comment]
I can't comment on the implementation (I don't know Python well), other than to say that, at minimum, this needs a bunch of tests.

**Comment by mathgeekcoder** [comment]
> I can't comment on the implementation (I don't know Python well), other than to say that, at minimum, this needs a bunch of tests.

Agreed.  Working on this now, will update PR.  BTW: the code changes for immutability are very simple.  The chained comparison support definitely needs more testing, and I believe I've already found a couple of edge cases that need attention.

**Comment by mathgeekcoder** [comment]
Abandoning this PR, as it has been replaced by #1942.

**Comment by mathgeekcoder** [comment]
Abandoning this PR, as it has been replaced by #1942.

**Pull request closed without merging**
