### PR TITLE
Fix objective sense input to assessHessian

### LINKED ISSUE #736: Bug: PSD check for maximization quadratic programs fails
When calling `passHessian`, HiGHS does not take the objective sense into account when computing semi definiteness:
```
julia> highs = Highs_create()
Ptr{Nothing} @0x00007fea23874400

julia> Highs_addCol(highs, 0.0, 0.0, Inf, 0, C_NULL, C_NULL)
0

julia> Highs_changeObjectiveSense(highs, -1)
0

julia> Highs_passHessian(
           highs,
           1,
           1,
           1, # kTriangular
           Cint[0],
           Cint[0],
           Cdouble[-2.0],
       )
ERROR:   Hessian has 1 diagonal entries in [-2, 0) so is not positive semidefinite
-1
```

### PR DESCRIPTION
**Pull request by odow**
Closes #736.

I think this is sufficient. But there might be other implications of solving maximization QPs? Doesn't look like they are well tested.

### CODE REVIEW

**Comment by jajhall** [comment]
Thanks for this. I'll fix the 64-bit bug

**Comment by jajhall** [comment]
Indeed, QP maximization not tested well! There was none in the C++ unit tests, and the only other was the one @odow introduced in `TestCAPI.c`. When maximizing, `Highs::callSolveQp()` only negates the cost vector, not the Hessian. Bug not exposed in the @odow example since it's max -x^2, so the turning point is the same whether or not the Hessian is negated!

**Review by jajhall — APPROVED** [review]
For me there is now sufficient testing of max QPs, and the process exposed several bugs that have now been fixed

**Comment by feldmeier** [comment]
looks good to me - thanks for fixing this!

**Pull request merged**
