### PR TITLE
reject quadratic constraints in FilereaderLp

### PR DESCRIPTION
**Pull request by svigerske**
Instead of ignoring the quadratic coefficients.

Triggered by http://listserv.zib.de/pipermail/scip/2023-July/004699.html

### CODE REVIEW

**Comment by jajhall** [comment]
Thanks, I'd noticed that HiGHS found this problem to be infeasible rather easily 😁

I'll fix the errors (formatting?), add a unit test - if you've not done so - and merge to latest

**Comment by svigerske** [comment]
`test-clang-format` was actually passing. I couldn't really understand the logs of the many failing tests, but they just seem to be much too long that it is easy to see where a failure is. After download, I see
```
2023-07-29T09:30:58.9469278Z -------------------------------------------------------------------------------
2023-07-29T09:30:58.9469476Z lp-file-format-quad-no-space
2023-07-29T09:30:58.9469789Z -------------------------------------------------------------------------------
2023-07-29T09:30:58.9469986Z /home/runner/work/HiGHS/HiGHS/check/TestLPFileFormat.cpp:8
2023-07-29T09:30:58.9470176Z ...............................................................................
2023-07-29T09:30:58.9470188Z 
2023-07-29T09:30:58.9470401Z /home/runner/work/HiGHS/HiGHS/check/TestLPFileFormat.cpp:13: FAILED:
2023-07-29T09:30:58.9470602Z   REQUIRE( highs.readModel(filename) == HighsStatus::kOk )
2023-07-29T09:30:58.9470704Z with expansion:
2023-07-29T09:30:58.9470809Z   -1 == 0
```
That looks related. I can try to fix that.

**Comment by svigerske** [comment]
I don't know why check "Documentation" would fail due to the changes here. I assume that this is unrelated.

**Comment by jajhall** [comment]
Yes the documentation failure is a current feature of the HiGHS CI tests that @galabovaa will fix in due course

**Pull request merged**
